apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tetris-deployment"
spec:
  selector:
    matchLabels:
      app: "tetris"
  replicas: 2
  template:
    metadata:
      labels:
        app: "tetris"
    spec:
      containers:
      - image: konradschieban/tetris
        imagePullPolicy: Always
        name: "tetris"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "svc-tetris"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: "tetris"
