---
- hosts: all
  become: true
  tasks:
    - name: Install Packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - container-selinux
        state: present

    - name: ADD Docker Repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      shell: yum install -y docker-ce-18.06.2.ce

    - name: Create Directory
      file:
        path: /etc/docker
        state: directory

    - name: Create Directory2
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
 
    - name: Copy daemon.json
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json

    - name: Docker start
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
        enabled: yes
