---
- hosts: all
  become: true
  tasks:
    - name: docker-compose install
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose

    - name: docker-compose permission
      file:
        path: /usr/local/bin/docker-compose
        mode: u+x,g+x,o+x

    - shell: /usr/local/bin/docker-compose --version
      register: result
