---
- hosts: master
  become: true
  tasks:
    - name: Mapping Private_DNS & Hostname
      shell: hostnamectl set-hostname $(curl http://169.254.169.254/latest/meta-data/local-hostname)
  
    - name: Reset kubeadm
      shell: kubeadm reset -f

    - name: Init kubeadm
      shell: kubeadm init --config /root/aws_k8s_test/04.single-cluster-create/master.yml
      register: output
    - debug: msg="{{ output }}"

    - name: Set user enviroment
      file:
        path: /root/.kube
        state: directory
    - name: Set user enviroment
      shell: |
        cp -i /etc/kubernetes/admin.conf /root/.kube/config
        chown root:root /root/.kube/config

    - name: Install Pod network add-on (Calico)
      shell: kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/calico.yaml

    - name: Set taint (Do not schedule pods)
      command: kubectl taint nodes --all node-role.kubernetes.io/master-

- hosts: workers
  become: true
  tasks:
    - name: Mapping Private_DNS & Hostname
      shell: hostnamectl set-hostname $(curl http://169.254.169.254/latest/meta-data/local-hostname)

    - name: Copy worker.yml
      copy:
        src: worker.yml
        dest: /root/
