---
- hosts: master
  become: true
  tasks:
    - name: Create token 
      shell: |
        kubeadm token create --print-join-command > token.sh

- hosts: workers
  become: true
  tasks:
    - name: Copy token.sh
      copy:
        src: token.sh
        dest: /tmp/

    - name: Join Cluster
      shell: sh /tmp/token.sh
      
