---
- hosts: master
  become: true
  tasks:
    - name: Create token 
      shell: |
        kubeadm token create --print-join-command > /root/aws_k8s_test/04.single-cluster-create/token.sh

- hosts: workers
  become: true
  tasks:
    - name: Copy token.sh
      copy:
        src: token.sh
        dest: /tmp/

    - name: Join Cluster
      shell: sh /tmp/token.sh
