---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: # kubeadm init에서 출력된 토큰을 입력
    apiServerEndpoint: ":6443" # API 서버의 엔드포인트를 입력
    caCertHashes:
      - # kubeadm init에서 출력된 caCert 해시 값을 입력
nodeRegistration:
  name: # 워커 노드의 Private DNS 이름을 입력
  kubeletExtraArgs:
    cloud-provider: aws
