apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc-nodeport
spec:
  selector:
    app: hello-node
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  type: NodePort
