---
- hosts: master
  become: true
  tasks:
    - name: Deploy is common-script
      command: /usr/bin/scp /root/aws_k8s_test/ansible/k8s-common.sh root@w1:/root/
    - name: Deploy is common-script
      command: /usr/bin/scp /root/aws_k8s_test/ansible/k8s-common.sh root@w2:/root/

- hosts: master
  become: true
  tasks:
    - name: Kubernetes install
      shell: /root/aws_k8s_test/ansible/k8s-common.sh

- hosts: workers
  become: true
  tasks:
    - name: Kubernetes install
      shell: /root/k8s-common.sh
