---
- hosts: all
  become: true
  tasks:
    - name: Create a repository file for Kubernetes
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch

    - name: Add repository details in kubernetes repo file
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=0
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kube*

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Disabling Swap on all nodes
      shell: swapoff -a

    - name: Commenting Swap entries in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '(.*swap*)'
        replace: '#\1'

    - name: Set IP Forward
      shell: "echo '1' > /proc/sys/net/ipv4/ip_forward"

    - name: Create a k8s.conf
      file:
        path: /etc/sysctl.d/k8s.conf
        state: touch

    - name: Enable Bridge Firewall Rule
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: sysctl --system
      shell: sysctl --system

    - name: Install Kubernetes
      shell: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

    - name: Start kubelet
      shell: |
        systemctl enable kubelet

