apiVersion: v1
kind: Service
metadata:
  name: hostname-service
#  namespace: ingress-nginx

spec:
  ports:
    - name: http
      port: 80
      targetPort: flask-port
  selector:
    app: hostname-service-label

  type: ClusterIP
